### PR TITLE
new features

### PR DESCRIPTION
**Pull request by farooq13**

### CODE REVIEW

**Comment by Rachit74** [comment]
@farooq13 I read your code and cloned and tested it on my machine, you did really great work but I think there can be improvements.
#### Likes and Dislikes fields in Post Model
I see you have made likes and dislikes field in post model which will have many to many relationship with User Model.
```python
likes = models.ManyToManyField(User, related_name='likes', blank=True)
dislikes = models.ManyToManyField(User, related_name='dislikes', blank=True)
```
but I think we can do this buy One to Many field with User field.
```python
class PostLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='likes')
```
I think by this code will be more structured

#### Single Like and Dislike view
I think we can handle the logic of Like and Dislike in single view
```python
class LikeDislikeHandlerView(View):
    def post(self, request, post_id, *args, **kwargs):
        post = get_object_or_404(Post, pk=post_id)
        user = request.user

        # Handle Like Logic
        if post.likes.filter(user=user).exists():
            # User has already liked the post; do nothing
            return HttpResponseRedirect(request.POST.get('next', '/'))

        if post.dislikes.filter(user=user).exists():
            # User has disliked the post in past, so remove dislike and add like
            post.dislikes.remove(user)
            Notification.objects.create(
                notification_type=1,
                from_user=user,
                to_user=post.author,
                post=post
            )

        # Add the like
        post.likes.add(user)

        # Handle Dislike Logic
        if post.dislikes.filter(user=user).exists():
            # User has already disliked the post; do nothing
            return HttpResponseRedirect(request.POST.get('next', '/'))

        if post.likes.filter(user=user).exists():
            # User liked the post, so remove like and add dislike
            post.likes.remove(user)

        # Add the dislike
        post.dislikes.add(user)

        # Redirect after handling the request
        return HttpResponseRedirect(request.POST.get('next', '/'))
```

I think rest is okay, there could be some improvements on the UI as it does not look the best, but that's can be done after the backend code has been refactored!

**Comment by farooq13** [comment]
yes of course!. Thanks for the improvement.

**Comment by Rachit74** [comment]
Hey @farooq13 did you made the improvements? if yes you can open a new PR

**Comment by farooq13** [comment]
I think using ``ManyToMany`` field in models.py for post --> likes/dislikes is ok since a single user can like/dislike many posts and 1 post can be liked by many users. In addition using separate view for Like and Dislike is not bad since we have 2 buttons one for Like and the other for Dislike to allow a user like/dislike based on his opinion. I tried your logic but unfortunately couldn't achieve the best by my side. I refactored the Like/Dislike logic making cleaner than before.

**Comment by Rachit74** [comment]
@farooq13 okay :+1:

**Comment by farooq13** [comment]
Thanks.

**Pull request closed without merging**
